import { GoogleGenAI } from '@google/genai';
import type { TryOnMode } from '@mrrx/shared';

// Initialize Gemini client
const client = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

// Model - Gemini 2.0 Flash for image generation (Nano Banana 3 Pro)
const IMAGE_MODEL = 'gemini-2.0-flash-exp-image-generation';
const TEXT_MODEL = 'gemini-2.0-flash';

type Gender = 'male' | 'female';

/**
 * Ultra-precise face preservation prompt
 * Emphasizes COPYING the exact face, not generating a similar one
 */
const buildUltraPrecisePrompt = (gender: Gender, mode: TryOnMode): string => {
  const person = gender === 'female' ? 'woman' : 'man';
  const pronoun = gender === 'female' ? 'her' : 'his';

  return `CRITICAL TASK: Photo-realistic virtual try-on with EXACT face preservation.

You MUST create an image where the EXACT SAME PERSON from the first photo is wearing the clothing from the second photo.

🚨 ABSOLUTE REQUIREMENT - FACE IDENTITY:
The face in your output MUST be the EXACT face from Photo 1. Not similar - IDENTICAL.
- Copy every facial feature EXACTLY: eyes, nose, lips, eyebrows, face shape, skin texture
- Copy exact skin tone, any moles, birthmarks, freckles in their exact positions
- Copy exact hair color, style, and texture
- The person's friends and family MUST be able to recognize them instantly
- If the face looks different AT ALL, you have FAILED the task

Think of it as: Take Photo 1's face and body, dress them in Photo 2's clothes.

📸 PHOTO 1 (FIRST IMAGE): The ${person} whose EXACT face and body must appear in output
📸 PHOTO 2 (SECOND IMAGE): The clothing/outfit to put on ${pronoun}

${mode === 'FULL_FIT' ? `
FULL OUTFIT MODE:
- Use the garment from Photo 2 as the main piece
- Create a complete coordinated outfit
- Add matching bottom wear, accessories, footwear
- Full body shot showing the complete look
` : `
SINGLE ITEM MODE:
- Place ONLY the garment from Photo 2 on the person
- Keep the rest of ${pronoun} outfit as appropriate
- Focus on how this specific garment fits ${pronoun}
`}

OUTPUT REQUIREMENTS:
- Ultra high quality, 4K resolution feel
- Professional fashion photography lighting
- Sharp details on face and clothing
- Realistic fabric texture and draping
- Natural body proportions matching Photo 1
- The face MUST pass identity verification - same person, not a look-alike

Generate the try-on image now. Remember: The face must be PIXEL-PERFECT identical to Photo 1.`;
};

/**
 * Generate virtual try-on image using Gemini
 * Maximum quality settings, pure Gemini - no face swap
 */
export async function generateTryOnImage(
  selfieBase64: string,
  productBase64: string,
  mode: TryOnMode = 'PART',
  gender: Gender = 'female',
  _feedbackContext?: string
): Promise<string> {
  try {
    // Clean base64 strings
    const cleanSelfie = selfieBase64.replace(/^data:image\/\w+;base64,/, '');
    const cleanProduct = productBase64.replace(/^data:image\/\w+;base64,/, '');

    const person = gender === 'female' ? 'woman' : 'man';
    const prompt = buildUltraPrecisePrompt(gender, mode);

    console.log('Generating try-on with Gemini (ultra-precise face mode)...');

    // Generate with maximum quality settings
    const response = await client.models.generateContent({
      model: IMAGE_MODEL,
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: `🎯 PHOTO 1 - THIS IS THE PERSON (${person.toUpperCase()}) - COPY THIS EXACT FACE TO OUTPUT:`
            },
            {
              inlineData: {
                mimeType: 'image/jpeg',
                data: cleanSelfie,
              },
            },
            {
              text: `👗 PHOTO 2 - THIS IS THE CLOTHING - PUT THIS ON THE PERSON FROM PHOTO 1:`
            },
            {
              inlineData: {
                mimeType: 'image/jpeg',
                data: cleanProduct,
              },
            },
            { text: prompt },
          ],
        },
      ],
      config: {
        responseModalities: ['IMAGE'],
      },
    });

    // Extract high-quality image from response
    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content?.parts || [];

      for (const part of parts) {
        if (part.inlineData?.mimeType?.startsWith('image/')) {
          const mimeType = part.inlineData.mimeType;
          const data = part.inlineData.data;
          console.log('Try-on image generated successfully');
          return `data:${mimeType};base64,${data}`;
        }
      }

      // Log any text response for debugging
      for (const part of parts) {
        if (part.text) {
          console.log('Model text response:', part.text.substring(0, 500));
        }
      }
    }

    throw new Error('No image generated by model');

  } catch (error) {
    console.error('Gemini generation error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    throw new Error(`Image generation failed: ${message}`);
  }
}

/**
 * Get style recommendations for an outfit
 */
export async function getStyleRecommendations(productBase64: string): Promise<{
  analysis: string;
  stylingTips: string[];
  complementaryItems: Array<{
    type: string;
    description: string;
    color: string;
    priceRange: string;
    searchQuery: string;
  }>;
}> {
  try {
    const cleanProduct = productBase64.replace(/^data:image\/\w+;base64,/, '');

    const prompt = `Analyze this fashion item and provide styling recommendations for Indian consumers.

Return a JSON object with:
- "analysis": Detailed description (type, style, color, material, occasion)
- "stylingTips": Array of 4-5 styling tips
- "complementaryItems": Array of 4-5 items to complete the outfit:
  - "type": Category (Jeans, Trousers, Sneakers, Watch, etc.)
  - "description": Specific recommendation
  - "color": Recommended color
  - "priceRange": Price in INR (e.g., "₹1,500 - ₹3,000")
  - "searchQuery": Search term for e-commerce sites

Focus on Indian fashion trends and items available on Myntra, Ajio, Amazon India.

Return ONLY the JSON object.`;

    const response = await client.models.generateContent({
      model: TEXT_MODEL,
      contents: [
        {
          role: 'user',
          parts: [
            { text: prompt },
            {
              inlineData: {
                mimeType: 'image/jpeg',
                data: cleanProduct,
              },
            },
          ],
        },
      ],
    });

    const text = response.candidates?.[0]?.content?.parts?.[0]?.text || '';
    const jsonMatch = text.match(/\{[\s\S]*\}/);

    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }

    return {
      analysis: 'Unable to analyze the item',
      stylingTips: [],
      complementaryItems: [],
    };
  } catch (error) {
    console.error('Style recommendations error:', error);
    return {
      analysis: 'Unable to analyze the item',
      stylingTips: [],
      complementaryItems: [],
    };
  }
}

export default {
  generateTryOnImage,
  getStyleRecommendations,
};
